### PR TITLE
Updating to use the new metrics tracker server for Pilot

### PR DESCRIPTION
**Pull request by animeshsingh**
@stevemart @scottdangelo

### CODE REVIEW

**Comment by scottdangelo** [comment]
I just merged changes to .travis.yml to get Travis CI to pass. Can you please pull latest master, rebase, and the push this up again?

**Comment by Tomcli** [comment]
sure

**Comment by Tomcli** [comment]
Moved this PR to #31

**Comment by stevemart** [comment]
close this in favor of https://github.com/IBM/watson-conversation-slots-intro/pull/32/files ?

**Pull request closed without merging**
